### ISSUE TITLE
Larvas immediately spawn and die upon hijack

### ISSUE THREAD

**Issue by token-map** [tgstation/TerraGov-Marine-Corps#7556]
### Description

Title. Whenever xenos hijack the dropship, a lot of larva in the queue suddenly pop out of the silo and die because they cant make it to the dropship in time.

### Test Merges

#7406: 'Super Rage Gives Ravager Bloodborne/Life Leech Slashing' by Surrealaser at commit 03c5d2d8df
#7442: 'Adds the HMG to marine vendors, HSG rebalance.' by Pariah919 at commit e32ae2d3b2
#7404: 'Sentry Rework' by hyper2snyper at commit deae5873c7

### Reproduction Steps

1. call dropship as queen/shrike
2. hijack the dropship
3. watch as several larva spawn and then promptly die because of hijack
4. shrike now has to call burrowed, with the larvas that died to hijack unable to respawn because of the respawn timer

**Comment by BraveMole** [comment]
I'm 90% sure i've fixed that already

**Comment by token-map** [comment]
![image](https://user-images.githubusercontent.com/73626246/126580370-d0720d63-4b10-40a9-bf35-fb7574cbb649.png)
![image](https://user-images.githubusercontent.com/73626246/126580661-3902506a-0a09-4c62-a1cb-d7194630c76c.png)
still isnt fixed, this was a round today

**Comment by token-map** [comment]
![image](https://user-images.githubusercontent.com/73626246/127581153-23f47195-6f2e-4946-bdc9-cfc9e9ee4318.png)
brrrrrrrrr (round: 10075)

**Comment by BraveMole** [comment]
So it's because cocoon are releasing victim on hijack, and are giving xeno larvas

**Comment by token-map** [comment]
fixed by #7823

**Comment by token-map** [comment]
fuck forgot to close
